#pragma once

// ENGINE
#define MAX_FPS 60
#define WINDOW_WIDTH 640 
#define WINDOW_HEIGHT 480 

// RENDERING
#define FOG_MIN_DISTANCE 3.0
#define FOG_MAX_DISTANCE 15.0
#define MINIMAP_SCALE 4

// PLAYER
#define PLAYER_WALK_SPEED 0.5
#define PLAYER_RUN_SPEED 1.5
#define PLAYER_ROTATION_SPEED 1.0
